const projects={
gul:{title:'Gul Bakes',intro:'A Shopify bakery project combining store development, visual content and digital marketing.',goal:'Create a clear online shopping experience for cakes and desserts.',work:['Organized cake and dessert products into collections and navigation.','Worked on storefront styling, product content and brand visuals.','Connected the project story with social media marketing and Brevo email marketing.','Documented the store and presented the project as part of e-commerce learning.'],tools:['Shopify','Brevo','Canva','Meta Business Suite'],learning:'This project brought store setup, brand communication and the customer journey together.'},
eloria:{title:'Eloria',intro:'A jewelry e-commerce project focused on an organized storefront and clear product discovery.',goal:'Present rings, earrings, bracelets and necklaces through a coherent jewelry store.',work:['Planned product collections and navigation.','Worked on banners, product presentation and store content.','Developed a structure for store information and shopping policies.'],tools:['Shopify','Canva','Product SEO'],learning:'The work explored how navigation and consistent visual content support a shopping experience.'},
retail:{title:'Retail Sales Analysis',intro:'A data analysis learning project using retail sales data.',goal:'Organize data and present useful patterns in a readable format.',work:['Worked with spreadsheet-based sales data.','Used charts and structured presentation to communicate the analysis.','Prepared the project files for a portfolio repository.'],tools:['Microsoft Excel','Data visualization','GitHub'],learning:'The project developed practice in turning raw data into understandable information.'},
robot:{title:'Sumo Robot',intro:'A practical robotics project using an ESP32-based control system.',goal:'Explore how electronics and programming work together in a mobile robot.',work:['Worked on a sumo robot project.','Explored ESP32 Wi-Fi control and PWM mapping.','Connected classroom concepts with practical testing.'],tools:['ESP32','Wi-Fi control','PWM'],learning:'The project provided hands-on experience with control logic and iterative testing.'},
tax:{title:'PakTax GraphAI',intro:'A Streamlit project developed in the context of the CUST SE Hackathon.',goal:'Explore a tax-focused application through a hackathon project.',work:['Developed a Streamlit-based project concept and interface.','Participated in the CUST hackathon experience.'],tools:['Python','Streamlit'],learning:'The hackathon offered practice in taking a technical idea into a working project under time constraints.'},
cargo:{title:'SwiftCargo',intro:'An academic project management assignment.',goal:'Apply project management learning to a cargo business scenario.',work:['Prepared project planning and assignment documentation.','Explored the structure needed to communicate a business project.'],tools:['Project planning','Documentation'],learning:'This coursework focused on organizing and explaining a project clearly.'},
fashion:{title:'AI Fashion Assistant',intro:'An exploratory project concept, not a launched product.',goal:'Explore a digital assistant that suggests outfits and accessories using a person’s preferences and budget.',work:['Outlined a potential user journey and input requirements.','Considered outfit, color and accessory recommendations.'],tools:['Concept development','AI exploration'],learning:'This idea connects an interest in artificial intelligence with a consumer-facing experience.'}
};
const dialog=document.getElementById('case-dialog');
let opener;
for(const button of document.querySelectorAll('[data-case]'))button.addEventListener('click',()=>{const p=projects[button.dataset.case];opener=button;document.getElementById('case-body').innerHTML=`<h2 id="case-title">${p.title}</h2><p>${p.intro}</p><h3>Purpose</h3><p>${p.goal}</p><h3>Project work</h3><ul>${p.work.map(w=>`<li>${w}</li>`).join('')}</ul><div class="tags">${p.tools.map(t=>`<span>${t}</span>`).join('')}</div><h3>Learning</h3><p>${p.learning}</p>`;dialog.showModal();document.body.classList.add('modal-open');});
dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');opener?.focus();});
const reduce=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduce.matches;const motion=document.querySelector('.motion');function setMotion(){document.body.classList.toggle('no-motion',paused);motion.setAttribute('aria-pressed',String(paused));motion.textContent=paused?'Enable motion':'Pause motion';motion.title=paused?'Turn on animation':'Turn off animation';}setMotion();motion.addEventListener('click',()=>{paused=!paused;setMotion();});reduce.addEventListener('change',e=>{paused=e.matches;setMotion();});
if('IntersectionObserver' in window){document.body.classList.add('js');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));}
for(const card of document.querySelectorAll('.tilt')){card.addEventListener('pointermove',e=>{if(paused||reduce.matches||e.pointerType!=='mouse')return;const r=card.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1100px) rotateX(${-y*5}deg) rotateY(${x*7}deg) translateY(-3px)`;});card.addEventListener('pointerleave',()=>card.style.transform='');}
