import {STATUSES,uid,today,day,metrics,blockers,taskError,validateBackup,demoProject} from './core.js';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='flowdesk-v1';let state,view='overview',filter='',priority='All',editing=null,storageBlocked=false;
try{const raw=localStorage.getItem(KEY);state=raw?validateBackup(JSON.parse(raw)):{version:1,projects:[demoProject()]};}catch(e){state={version:1,projects:[demoProject()]};storageBlocked=true;$('#notice').hidden=false;$('#notice').textContent='Saved data could not be read. The demo is shown without overwriting it. Export this session before closing; import a valid backup to resume saving.';}
let active=state.projects[0].id;
const project=()=>state.projects.find(p=>p.id===active);
const money=n=>new Intl.NumberFormat('en-PK',{style:'currency',currency:project().currency,maximumFractionDigits:0}).format(n);
const date=s=>new Date(s+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short'});
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,4500);}
function persist(){if(storageBlocked){toast('Session updated. Export a backup: browser saving is unavailable.');return;}try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){storageBlocked=true;$('#notice').hidden=false;$('#notice').textContent='Browser storage is unavailable or full. Changes are kept only in this open tab. Export a backup before leaving.';}}
function log(text){project().activity.unshift({at:new Date().toISOString(),text});project().activity=project().activity.slice(0,200);}
function badge(s,kind=''){return `<span class="badge ${kind}">${esc(s)}</span>`;}
function empty(text){return `<div class="empty">${text}</div>`;}
function navigate(v){view=v;filter='';priority='All';location.hash=v;render();}
const labels={overview:'Overview',board:'Task board',timeline:'Timeline',risks:'Risk register',changes:'Change requests',activity:'Activity'};
function render(){const p=project(),m=metrics(p);$('#project-select').innerHTML=state.projects.map(x=>`<option value="${esc(x.id)}" ${x.id===active?'selected':''}>${esc(x.name)}</option>`).join('');$('#project-title').textContent=p.name;$('#project-description').textContent=p.description;$('#project-mode').textContent=p.demo?'DEMO PROJECT / SYNTHETIC DATA':'PERSONAL PROJECT / LOCAL WORKSPACE';$('#breadcrumb').textContent='WORKSPACE / '+labels[view].toUpperCase();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#add').textContent=view==='risks'?'+ Add risk':view==='changes'?'+ Request change':'+ Add task';const banner=p.demo?'<div class="demo-banner"><strong>A space to learn by doing.</strong><span>This demo uses illustrative tasks and costs. Create a new project for your own work.</span></div>':'';$('#content').innerHTML=banner+({overview:overview,board:board,timeline:timeline,risks:risks,changes:changes,activity:activity}[view])(p,m);}
function overview(p,m){const alerts=p.tasks.filter(t=>t.status!=='Done').sort((a,b)=>a.due.localeCompare(b.due)).slice(0,5);return `<div class="metrics"><div class="metric"><label>Project completion</label><strong>${m.progress}%</strong><small>${m.done} of ${m.total} tasks completed</small></div><div class="metric ${m.overdue?'alert':''}"><label>Overdue tasks</label><strong>${m.overdue}</strong><small>Compared with today’s date</small></div><div class="metric"><label>Recorded cost</label><strong style="font-size:23px">${money(m.actual)}</strong><small>Sum of task actual costs</small></div><div class="metric ${m.highRisks?'alert':''}"><label>High open risks</label><strong>${m.highRisks}</strong><small>Probability × impact ≥ 12</small></div></div><div class="overview-grid"><div><section class="panel"><div class="panel-heading"><h2>What needs your attention</h2><button data-nav="board">View all tasks →</button></div>${alerts.length?alerts.map(t=>`<div class="focus-item"><div><button data-edit-task="${esc(t.id)}">${esc(t.title)}</button><p>${esc(t.owner||'Unassigned')} · Due ${date(t.due)}</p></div>${t.due<today()?badge('Overdue','red'):blockers(p,t).length?badge('Dependency','high'):badge(t.status,'blue')}</div>`).join(''):empty('No open tasks. Add a task to plan your next step.')}</section><section class="panel"><div class="panel-heading"><h2>Recent activity</h2><button data-nav="activity">View log →</button></div>${p.activity.slice(0,3).map(a=>`<div class="activity-item">${esc(a.text)}<time>${esc(new Date(a.at).toLocaleString())}</time></div>`).join('')||empty('Your project activity will appear here.')}</section></div><div><section class="panel"><div class="panel-heading"><h2>Delivery progress</h2>${badge(m.blocked+' dependent','blue')}</div><div class="progress-track" aria-label="${m.progress}% complete"><span style="width:${m.progress}%"></span></div>${STATUSES.map(s=>`<div class="status-row"><span>${s}</span><strong>${p.tasks.filter(t=>t.status===s).length}</strong></div>`).join('')}<div class="callout">Task completion is count-based. It does not measure effort or earned value.</div></section><section class="panel"><h2>Budget control</h2><div class="budget-number">${money(m.remaining)}</div><p class="budget-note">${m.remaining<0?'Over the approved budget':'Remaining approved budget'}</p><div class="status-row"><span>Original budget</span><strong>${money(p.budget)}</strong></div><div class="status-row"><span>Approved changes</span><strong>${money(m.adjustment)}</strong></div><div class="status-row"><span>Task estimates</span><strong>${money(m.estimate)}</strong></div><div class="status-row"><span>Approved budget</span><strong>${money(m.budget)}</strong></div>${m.estimate>m.budget?'<div class="callout">Task estimates exceed the approved budget. Review scope and cost assumptions.</div>':''}<button data-nav="changes" style="width:100%;margin-top:16px">Review ${m.pending} pending changes</button></section></div></div>`;}
function taskCard(p,t){const b=blockers(p,t);return `<article class="task">${badge(t.priority+' priority',t.priority==='High'?'high':'')}<button class="task-title" data-edit-task="${esc(t.id)}">${esc(t.title)}</button>${b.length?`<div class="blocked">Waiting for ${b.length} predecessor${b.length>1?'s':''}</div>`:''}<div class="task-meta"><span>${esc(t.owner||'Unassigned')}</span><span>${t.due<today()&&t.status!=='Done'?'Late · ':''}${date(t.due)}</span></div><select data-task-status="${esc(t.id)}" aria-label="Status for ${esc(t.title)}">${STATUSES.map(s=>`<option ${s===t.status?'selected':''}>${s}</option>`).join('')}</select></article>`;}
function board(p){return `<div class="toolbar"><h2 class="view-title">Your task board</h2><select id="priority-filter" aria-label="Filter by priority">${['All','High','Medium','Low'].map(x=>`<option ${priority===x?'selected':''}>${x}</option>`).join('')}</select><input id="task-search" type="search" placeholder="Search tasks or owners…" aria-label="Search tasks" value="${esc(filter)}"></div><div class="board">${STATUSES.map(s=>{const tasks=p.tasks.filter(t=>t.status===s&&(priority==='All'||t.priority===priority)&&(t.title+' '+t.owner).toLowerCase().includes(filter.toLowerCase()));return `<section class="column"><div class="column-title">${s}<span>${tasks.length}</span></div>${tasks.map(t=>taskCard(p,t)).join('')||empty('No matching tasks')}</section>`;}).join('')}</div><p class="project-data-note">Select a task to edit it. Status controls work with touch and keyboard. Predecessors must be done before dependent work can start.</p>`;}
function timeline(p){if(!p.tasks.length)return empty('Add tasks with start and due dates to see the timeline.');const start=Math.min(...p.tasks.map(t=>day(t.start))),end=Math.max(...p.tasks.map(t=>day(t.due))),span=end-start+1;return `<div class="toolbar"><h2 class="view-title">Planned timeline</h2><span class="muted">Calendar days · dates are manually scheduled</span></div><div class="timeline"><div class="timeline-inner"><div class="timeline-header"><strong>Work package</strong><div><span>${date(p.tasks.reduce((a,t)=>t.start<a?t.start:a,p.tasks[0].start))}</span><span>${span} days</span><span>${date(p.tasks.reduce((a,t)=>t.due>a?t.due:a,p.tasks[0].due))}</span></div></div>${[...p.tasks].sort((a,b)=>a.start.localeCompare(b.start)).map(t=>`<div class="timeline-row"><button data-edit-task="${esc(t.id)}">${esc(t.title)}<br><span class="muted" style="font-size:10px">${date(t.start)} – ${date(t.due)}</span></button><div class="timeline-track" aria-label="${esc(t.title)}: ${date(t.start)} to ${date(t.due)}"><div class="timeline-bar ${t.status==='Done'?'done':t.due<today()?'late':''}" style="left:${(day(t.start)-start)/span*100}%;width:${(day(t.due)-day(t.start)+1)/span*100}%"></div>${day(today())>=start&&day(today())<=end?`<div class="timeline-marker" title="Today" style="left:${(day(today())-start)/span*100}%"></div>`:''}</div></div>`).join('')}</div></div><p class="project-data-note">Blue: planned work · Green: complete · Amber: overdue · Dark line: today. Dependencies control task status; they do not automatically move dates.</p>`;}
function risks(p){return `<div class="toolbar"><h2 class="view-title">Risks and responses</h2><span class="muted">High ≥12 · Medium 6–11 · Low 1–5</span></div>${!p.risks.length?empty('No risks recorded. Add an uncertainty and plan a response.'):`<div class="table-wrap"><table><thead><tr><th>RISK / RESPONSE</th><th>OWNER</th><th>P × I</th><th>EXPOSURE</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>${[...p.risks].sort((a,b)=>b.probability*b.impact-a.probability*a.impact).map(r=>{const score=r.probability*r.impact;return `<tr><td><div class="risk-name">${esc(r.title)}</div><p>${esc(r.response||'Response not yet defined')}</p></td><td>${esc(r.owner||'Unassigned')}</td><td>${r.probability} × ${r.impact}</td><td>${badge(score+' / '+(score>=12?'High':score>=6?'Medium':'Low'),score>=12?'red':score>=6?'high':'green')}</td><td>${badge(r.status,r.status==='Closed'?'green':'blue')}</td><td><button data-edit-risk="${esc(r.id)}">Edit risk</button></td></tr>`;}).join('')}</tbody></table></div>`}<p class="project-data-note">Probability: 1 rare, 5 very likely. Impact: 1 minor, 5 severe. Scores help prioritize discussion; they are not statistical probabilities.</p>`;}
function changes(p){return `<div class="toolbar"><h2 class="view-title">Scope and budget decisions</h2></div>${!p.changes.length?empty('No changes requested. Record proposals before changing the baseline.'):`<div class="table-wrap"><table><thead><tr><th>REQUEST / REASON</th><th>BUDGET IMPACT</th><th>SCHEDULE IMPACT</th><th>DECISION</th><th>ACTION</th></tr></thead><tbody>${p.changes.map(c=>`<tr><td><div class="risk-name">${esc(c.title)}</div><p>${esc(c.reason)}</p></td><td>${money(c.amount)}</td><td>${c.days>0?'+':''}${c.days} days</td><td>${badge(c.status,c.status==='Approved'?'green':c.status==='Rejected'?'red':'high')}<p>${esc(c.decision)}</p></td><td><button data-edit-change="${esc(c.id)}">${c.status==='Pending'?'Review':'View decision'}</button></td></tr>`).join('')}</tbody></table></div>`}<div class="panel" style="margin-top:24px"><p class="muted" style="margin:0">Approval updates the project’s approved budget. Schedule impact is recorded for review; update affected task dates separately. Decisions are local planning records, not approvals from another person.</p></div>`;}
function activity(p){return `<section class="panel"><div class="panel-heading"><h2>Project activity</h2><span class="muted">Latest 200 events</span></div>${p.activity.map(a=>`<div class="activity-item">${esc(a.text)}<time>${esc(new Date(a.at).toLocaleString())}</time></div>`).join('')||empty('Changes to this project will appear here.')}</section>`;}
const field=(label,name,value='',type='text',extra='')=>`<label class="field">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const area=(label,name,value='')=>`<label class="field full">${label}<textarea name="${name}" maxlength="2000">${esc(value)}</textarea></label>`;
const select=(label,name,values,value)=>`<label class="field">${label}<select name="${name}">${values.map(s=>`<option ${s===value?'selected':''}>${esc(s)}</option>`).join('')}</select></label>`;
function openEditor(type,id){editing={type,id};const p=project();$('#form-error').textContent='';$('#delete-item').hidden=!id;$('#editor-form button[type=submit]').hidden=false;$('#delete-item').textContent='Delete';let html='';
if(type==='project'){const x=id?p:{name:'',description:'',budget:0,currency:'PKR'};$('#dialog-title').textContent=id?'Project settings':'Create a project';html=field('Project name','name',x.name,'text','required maxlength="120"')+select('Currency','currency',['PKR','USD','GBP','EUR'],x.currency)+field('Original budget','budget',x.budget,'number','min="0" max="1000000000" step="0.01" required')+area('Project objective','description',x.description);if(id&&x.demo)html+='<p class="field full muted">This is a labelled demo. Create a new project to track your own work.</p>';}
if(type==='task'){const t=p.tasks.find(t=>t.id===id)||{title:'',owner:'',start:today(),due:today(),status:'To do',priority:'Medium',estimate:0,actual:0,deps:[],notes:''};$('#dialog-title').textContent=id?'Edit task':'Add a task';html=field('Task title','title',t.title,'text','required maxlength="160"')+field('Owner','owner',t.owner,'text','maxlength="80"')+field('Start date','start',t.start,'date','required')+field('Due date','due',t.due,'date','required')+select('Status','status',STATUSES,t.status)+select('Priority','priority',['Low','Medium','High'],t.priority)+field('Estimated cost ('+p.currency+')','estimate',t.estimate,'number','min="0" max="1000000000" step="0.01" required')+field('Actual cost ('+p.currency+')','actual',t.actual,'number','min="0" max="1000000000" step="0.01" required')+`<label class="field full">Predecessors<select name="deps" multiple aria-label="Predecessors">${p.tasks.filter(x=>x.id!==id).map(x=>`<option value="${esc(x.id)}" ${t.deps.includes(x.id)?'selected':''}>${esc(x.title)}</option>`).join('')}</select><small>Optional. Hold Ctrl/Command to select or deselect several tasks on desktop.</small></label>`+area('Acceptance criteria and notes','notes',t.notes);}
if(type==='risk'){const r=p.risks.find(r=>r.id===id)||{title:'',owner:'',probability:3,impact:3,status:'Open',response:''};$('#dialog-title').textContent=id?'Review risk':'Add a risk';html=field('Risk statement','title',r.title,'text','required maxlength="160"')+field('Risk owner','owner',r.owner,'text','maxlength="80"')+select('Probability (1–5)','probability',[1,2,3,4,5],r.probability)+select('Impact (1–5)','impact',[1,2,3,4,5],r.impact)+select('Status','status',['Open','Closed'],r.status)+area('Response and trigger','response',r.response);}
if(type==='change'){const c=p.changes.find(c=>c.id===id)||{title:'',reason:'',amount:0,days:0,status:'Pending',decision:''};$('#dialog-title').textContent=id?'Review change request':'Request a change';html=field('Change title','title',c.title,'text','required maxlength="160"')+select('Decision','status',['Pending','Approved','Rejected'],c.status)+field('Budget impact ('+p.currency+')','amount',c.amount,'number','min="-1000000000" max="1000000000" step="0.01" required')+field('Schedule impact (days)','days',c.days,'number','min="-3650" max="3650" step="1" required')+area('Reason and expected benefit','reason',c.reason)+area('Decision rationale','decision',c.decision);if(c.status!=='Pending'){html='<p class="backup-warning">This decision is recorded. For a revision, create a new change request with the reversing or additional impact.</p>'+`<fieldset disabled style="border:0;padding:0"><div class="form-grid">${html}</div></fieldset>`;$('#editor-form button[type=submit]').hidden=true;$('#delete-item').hidden=true;}}
$('#fields').innerHTML='<div class="form-grid">'+html+'</div>';$('#editor').showModal();}
function saveEditor(e){e.preventDefault();const f=new FormData(e.currentTarget),p=project(),v=n=>String(f.get(n)||'').trim(),num=n=>Number(f.get(n)),id=editing.id||uid();let error='';
if(editing.type==='project'){const name=v('name'),budget=num('budget');if(!name||!Number.isFinite(budget)||budget<0)error='Enter a project name and a valid budget.';else if(editing.id&&v('currency')!==p.currency&&(p.tasks.length||p.changes.length))error='Currency cannot change after tasks or change requests are recorded.';else if(editing.id&&p.changes.some(c=>c.status==='Approved')&&(budget!==p.budget||v('currency')!==p.currency))error='Once changes are approved, adjust funding through a new change request. Currency is locked.';else if(editing.id){Object.assign(p,{name,description:v('description'),budget,currency:v('currency')});log('Project settings updated.');}else{if(state.projects.length>=30){error='A workspace supports up to 30 projects. Export and remove unused projects first.';}else{state.projects.push({id,name,description:v('description'),budget,currency:v('currency'),demo:false,tasks:[],risks:[],changes:[],activity:[]});active=id;view='overview';log('Project created.');}}}
if(editing.type==='task'){const t={id,title:v('title'),owner:v('owner'),start:v('start'),due:v('due'),status:v('status'),priority:v('priority'),estimate:num('estimate'),actual:num('actual'),deps:f.getAll('deps'),notes:v('notes')};error=taskError(p,t);if(!editing.id&&p.tasks.length>=500)error='This project supports up to 500 tasks.';if(!error){p.tasks=p.tasks.filter(x=>x.id!==id).concat(t);log((editing.id?'Updated task: ':'Created task: ')+t.title);}}
if(editing.type==='risk'){const r={id,title:v('title'),owner:v('owner'),probability:num('probability'),impact:num('impact'),response:v('response'),status:v('status')};if(!r.title)error='Enter a risk statement.';else if(!editing.id&&p.risks.length>=200)error='This project supports up to 200 risks.';else{p.risks=p.risks.filter(x=>x.id!==id).concat(r);log((editing.id?'Updated risk: ':'Added risk: ')+r.title);}}
if(editing.type==='change'){const old=p.changes.find(x=>x.id===id);if(old&&old.status!=='Pending')error='This decision is already recorded.';const c={id,title:v('title'),reason:v('reason'),amount:num('amount'),days:num('days'),status:v('status'),decision:v('decision')};if(!c.title||!Number.isFinite(c.amount)||!Number.isInteger(c.days))error='Enter a title and valid cost and whole-day impacts.';else if(c.status!=='Pending'&&!c.decision)error='Add a decision rationale before approving or rejecting.';else if(c.status==='Approved'&&metrics(p).budget+c.amount<0)error='This change would make the approved budget negative.';else if(!editing.id&&p.changes.length>=200)error='This project supports up to 200 changes.';if(!error){p.changes=p.changes.filter(x=>x.id!==id).concat(c);log(c.status+' change request: '+c.title);}}
if(error){$('#form-error').textContent=error;return;}persist();$('#editor').close();render();toast('Saved to your workspace.');}
$('#editor-form').addEventListener('submit',saveEditor);$('#close-dialog').onclick=$('#cancel-dialog').onclick=()=>$('#editor').close();
$('#delete-item').onclick=()=>{const p=project(),{type,id}=editing;if(type==='task'&&p.tasks.some(t=>t.deps.includes(id))){$('#form-error').textContent='Remove references from dependent tasks before deleting this task.';return;}if(type==='project'&&state.projects.length===1){$('#form-error').textContent='Create another project before deleting your only project.';return;}if(!confirm('Delete this '+type+'? This cannot be undone. Export a backup first if you need a copy.'))return;if(type==='project'){state.projects=state.projects.filter(x=>x.id!==id);active=state.projects[0].id;}else{const key={task:'tasks',risk:'risks',change:'changes'}[type];p[key]=p[key].filter(x=>x.id!==id);log('Deleted a '+type+'.');}persist();$('#editor').close();render();toast('Deleted.');};
$('#project-select').onchange=e=>{active=e.target.value;filter='';render();};$('#new-project').onclick=()=>openEditor('project');$('#edit-project').onclick=()=>openEditor('project',active);$('#add').onclick=()=>openEditor(view==='risks'?'risk':view==='changes'?'change':'task');
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)navigate(b.dataset.view);if(b.dataset.nav)navigate(b.dataset.nav);if(b.dataset.editTask)openEditor('task',b.dataset.editTask);if(b.dataset.editRisk)openEditor('risk',b.dataset.editRisk);if(b.dataset.editChange)openEditor('change',b.dataset.editChange);});
document.addEventListener('change',e=>{if(e.target.dataset.taskStatus){const p=project(),t=p.tasks.find(x=>x.id===e.target.dataset.taskStatus),next={...t,status:e.target.value};const error=taskError(p,next);if(error){toast(error);e.target.value=t.status;return;}t.status=next.status;log('Moved '+t.title+' to '+t.status+'.');persist();render();}if(e.target.id==='priority-filter'){priority=e.target.value;render();}});
document.addEventListener('input',e=>{if(e.target.id==='task-search'){const cursor=e.target.selectionStart;filter=e.target.value;render();const input=$('#task-search');input.focus();input.setSelectionRange(cursor,cursor);}});
function download(name,body,type){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#backup').onclick=()=>{download('flowdesk-backup-'+today()+'.json',JSON.stringify(state,null,2),'application/json');toast('Backup downloaded. Keep it somewhere you can find it.');};
$('#import').onclick=()=>$('#file-input').click();$('#file-input').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5000000)throw Error('Backup is too large. The limit is 5 MB.');const data=validateBackup(JSON.parse(await file.text()));if(data.projects.length+state.projects.length>30)throw Error('Import would exceed 30 projects.');for(const p of data.projects){p.id=uid();p.name=(p.name+' (imported)').slice(0,120);state.projects.push(p);}active=state.projects.at(-1).id;storageBlocked=false;$('#notice').hidden=true;persist();render();toast('Backup imported as new projects. Existing projects were kept.');}catch(err){toast('Import failed: '+err.message);}e.target.value='';};
$('#report').onclick=()=>{const p=project(),m=metrics(p);const lines=[`# ${p.name} — status report`,``, `Generated: ${new Date().toLocaleString()}`,`Data: ${p.demo?'ILLUSTRATIVE DEMO — not measured business results':'User-entered local project records'}`,'',p.description,'','## Summary',`- Completed: ${m.done}/${m.total} tasks (${m.progress}%)`,`- Overdue: ${m.overdue}`,`- Waiting on predecessors: ${m.blocked}`,`- Original budget: ${money(p.budget)}`,`- Approved changes: ${money(m.adjustment)}`,`- Approved budget: ${money(m.budget)}`,`- Recorded actual costs: ${money(m.actual)}`,`- Remaining budget: ${money(m.remaining)}`,`- High open risks: ${m.highRisks}`,`- Pending change requests: ${m.pending}`,'','## Tasks',...p.tasks.map(t=>`- ${t.title} | ${t.status} | Owner: ${t.owner||'Unassigned'} | Due: ${t.due} | Actual: ${money(t.actual)}`),'','## Open risks',...p.risks.filter(r=>r.status==='Open').map(r=>`- ${r.title} (${r.probability*r.impact}/25). Owner: ${r.owner||'Unassigned'}. Response: ${r.response||'Not defined'}`),'','## Decisions',...p.changes.map(c=>`- ${c.title}: ${c.status}. ${money(c.amount)}, ${c.days} days. ${c.decision}`),'','## Next steps','Add your management interpretation, decisions needed, and next-week commitments here.'];download('flowdesk-status-'+today()+'.md',lines.join('\n'),'text/markdown');toast('Status report downloaded. Add your interpretation before sharing.');};
window.addEventListener('hashchange',()=>{const v=location.hash.slice(1);if(labels[v]){view=v;render();}});const initial=location.hash.slice(1);if(labels[initial])view=initial;render();if(!storageBlocked)persist();
