export const STATUSES=['To do','In progress','Review','Done'];
export const uid=()=>globalThis.crypto?.randomUUID?.()||'id-'+Date.now().toString(36)+Math.random().toString(36).slice(2);
export function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function validDate(s){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s+'T12:00:00Z'))&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s;}
export const day=(s)=>Date.parse(s+'T12:00:00Z')/86400000;
export function offsetDate(n){const d=new Date();d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function blockers(p,t){return t.deps.map(id=>p.tasks.find(x=>x.id===id)).filter(x=>x&&x.status!=='Done');}
export function metrics(p,asOf=today()){const done=p.tasks.filter(t=>t.status==='Done').length;const actual=p.tasks.reduce((s,t)=>s+t.actual,0);const estimate=p.tasks.reduce((s,t)=>s+t.estimate,0);const adjustment=p.changes.filter(c=>c.status==='Approved').reduce((s,c)=>s+c.amount,0);return {done,total:p.tasks.length,progress:p.tasks.length?Math.round(done/p.tasks.length*100):0,actual,estimate,adjustment,budget:p.budget+adjustment,remaining:p.budget+adjustment-actual,overdue:p.tasks.filter(t=>t.status!=='Done'&&t.due<asOf).length,blocked:p.tasks.filter(t=>t.status!=='Done'&&blockers(p,t).length).length,highRisks:p.risks.filter(r=>r.status==='Open'&&r.probability*r.impact>=12).length,pending:p.changes.filter(c=>c.status==='Pending').length};}
export function taskError(p,t){if(!t.title.trim())return 'Enter a task title.';if(!validDate(t.start)||!validDate(t.due)||t.due<t.start)return 'Due date must be on or after the start date.';if(!Number.isFinite(t.estimate)||!Number.isFinite(t.actual)||t.estimate<0||t.actual<0)return 'Costs must be zero or positive numbers.';if(t.deps.some(id=>id===t.id||!p.tasks.some(x=>x.id===id)))return 'Choose valid predecessors; a task cannot depend on itself.';const all=p.tasks.filter(x=>x.id!==t.id).concat(t);const seen=new Set(),active=new Set();function visit(id){if(active.has(id))return true;if(seen.has(id))return false;active.add(id);const node=all.find(x=>x.id===id);if(node?.deps.some(visit))return true;active.delete(id);seen.add(id);return false;}if(all.some(x=>visit(x.id)))return 'This dependency would create a cycle.';if(t.status!=='To do'&&blockers(p,t).length)return 'Complete the predecessor tasks before starting this task.';if(t.status!=='Done'&&p.tasks.some(x=>x.id!==t.id&&x.status!=='To do'&&x.deps.includes(t.id)))return 'Move dependent tasks back to To do before reopening this predecessor.';return '';}
export function validateBackup(raw){if(raw?.version!==1||!Array.isArray(raw.projects)||raw.projects.length<1||raw.projects.length>30)throw Error('Choose a FlowDesk version 1 backup with 1–30 projects.');const text=(v,max=2000)=>{if(typeof v!=='string'||v.length>max)throw Error('Backup contains an invalid text field.');return v;};const num=(v,min=0)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<min)throw Error('Backup contains an invalid numeric field.');return v;};const enumValue=(v,a)=>{if(!a.includes(v))throw Error('Backup contains an unknown status.');return v;};const arr=(v,max)=>{if(!Array.isArray(v)||v.length>max)throw Error('Backup exceeds the supported number of records.');return v;};const date=v=>{if(!validDate(v))throw Error('Backup contains an invalid date.');return v;};
const projects=raw.projects.map(p=>({id:text(p.id,100),name:text(p.name,120),description:text(p.description),budget:num(p.budget),currency:enumValue(p.currency,['PKR','USD','GBP','EUR']),demo:p.demo===true,tasks:arr(p.tasks,500).map(t=>({id:text(t.id,100),title:text(t.title,160),owner:text(t.owner,80),start:date(t.start),due:date(t.due),status:enumValue(t.status,STATUSES),priority:enumValue(t.priority,['Low','Medium','High']),estimate:num(t.estimate),actual:num(t.actual),deps:arr(t.deps,500).map(x=>text(x,100)),notes:text(t.notes)})),risks:arr(p.risks,200).map(r=>({id:text(r.id,100),title:text(r.title,160),owner:text(r.owner,80),probability:enumValue(r.probability,[1,2,3,4,5]),impact:enumValue(r.impact,[1,2,3,4,5]),response:text(r.response),status:enumValue(r.status,['Open','Closed'])})),changes:arr(p.changes,200).map(c=>({id:text(c.id,100),title:text(c.title,160),reason:text(c.reason),amount:num(c.amount,-1000000000),days:num(c.days,-3650),status:enumValue(c.status,['Pending','Approved','Rejected']),decision:text(c.decision)})),activity:arr(p.activity,200).map(a=>({at:text(a.at,100),text:text(a.text)}))}));
for(const p of projects){if(!p.name.trim())throw Error('Project name is required.');for(const list of [p.tasks,p.risks,p.changes])if(new Set(list.map(x=>x.id)).size!==list.length)throw Error('Backup contains duplicate record IDs.');for(const t of p.tasks){const e=taskError(p,t);if(e)throw Error(e);}if(metrics(p).budget<0)throw Error('Approved budget cannot be negative.');}if(new Set(projects.map(x=>x.id)).size!==projects.length)throw Error('Backup contains duplicate projects.');return {version:1,projects};}
export function demoProject(){
const rows=[
['Project charter & success criteria','Quratulain Shakeel',-35,-33,'Done','High',2500,2500,[],'Define project purpose, scope, success criteria and evidence needed for the portfolio.'],
['Target audience & customer journey','Quratulain Shakeel',-33,-31,'Done','High',3000,3000,['gb-t0'],'Define customer groups, shopping needs and the discovery-to-order journey.'],
['Brand system & visual direction','Gulnaz Akhtar',-32,-29,'Done','High',4500,4500,['gb-t0'],'Lock the Gul Bakes visual system: Navy #172554, Blue #2563EB and White #FFFFFF.'],
['Shopify general settings','Quratulain Shakeel',-30,-27,'Done','High',2500,2500,['gb-t0'],'Review store identity, contact details, currency, checkout basics and customer-facing settings.'],
['Domain, payments, shipping & tax setup','Quratulain Shakeel',-28,-24,'Done','High',5000,5000,['gb-t3'],'Validate domain connection, payment method setup, Pakistan delivery rules and tax display.'],
['Product data preparation','Gulnaz Akhtar',-27,-23,'Done','High',4000,4000,['gb-t1','gb-t2'],'Prepare titles, descriptions, prices, images, variants/options and product grouping.'],
['Upload and QA products','Quratulain Shakeel',-24,-19,'Done','High',8000,8000,['gb-t5'],'Create product entries and verify images, pricing, availability, options and calls-to-action.'],
['Product SEO & alt text','Gulnaz Akhtar',-22,-18,'Done','Medium',4500,4500,['gb-t6'],'Improve searchable titles, meta descriptions, handles and image alt text without keyword stuffing.'],
['Build collections','Quratulain Shakeel',-20,-16,'Done','High',6000,6000,['gb-t6'],'Create and review Birthday Cakes, Chocolate Cakes, Vanilla Cakes, Cupcakes, New Arrivals, Best Sellers and Custom Cakes collections.'],
['Navigation & menu architecture','Quratulain Shakeel',-18,-14,'In progress','High',4500,2200,['gb-t8'],'Connect header/footer links to the correct collections, pages and customer-care content.'],
['Homepage structure & premium sections','Quratulain Shakeel',-17,-11,'In progress','High',12000,7000,['gb-t2','gb-t8'],'Build hero, categories, best sellers, custom cakes, Signature Details, Gift Edit, story, journal and trust sections.'],
['Custom cake ordering journey','Gulnaz Akhtar',-15,-10,'In progress','High',6500,2800,['gb-t6'],'Create a clear custom cake journey with inspiration, details, guidance and a strong order CTA.'],
['Product page UX & purchase controls','Quratulain Shakeel',-12,-8,'To do','High',5000,0,['gb-t9','gb-t10'],'Validate Add to Cart/Buy blocks, options, uploads and mobile product-page experience.'],
['Our Story, reviews & trust content','Gulnaz Akhtar',-11,-7,'To do','Medium',3500,0,['gb-t2'],'Complete brand story, customer reviews, trust badges and why-choose-us messaging.'],
['FAQ, contact & policy pages','Gulnaz Akhtar',-10,-5,'To do','Medium',3000,0,['gb-t3','gb-t4'],'Publish clear FAQ, contact, shipping, return/exchange, privacy and terms information.'],
['Blog / Gul Bakes Journal','Gulnaz Akhtar',-8,-3,'To do','Low',3000,0,['gb-t13'],'Prepare useful bakery/celebration articles with supporting images and internal links.'],
['Mobile & responsive QA','Quratulain Shakeel',-6,-1,'To do','High',5500,0,['gb-t10','gb-t11','gb-t12'],'Check spacing, one-line layouts, image crops, buttons, typography and section consistency on mobile.'],
['Facebook & Instagram business setup','Gulnaz Akhtar',-5,1,'To do','Medium',4000,0,['gb-t2'],'Align social profiles, brand description, visuals and content with the Shopify store.'],
['Meta catalog / WhatsApp commerce checks','Quratulain Shakeel',-3,3,'To do','Medium',4500,0,['gb-t6','gb-t17'],'Review product sync, catalog approvals, customer messaging and channel consistency.'],
['Brevo profile & sender setup','Gulnaz Akhtar',-2,2,'To do','Medium',3000,0,['gb-t0'],'Complete Brevo account/profile setup and sender information for Gul Bakes.'],
['Brevo contacts & segmentation','Gulnaz Akhtar',1,4,'To do','Medium',3000,0,['gb-t19'],'Organize contacts and create useful audience segments for email communication.'],
['Welcome email campaign','Quratulain Shakeel',3,7,'To do','High',5000,0,['gb-t20','gb-t2'],'Design and test a premium welcome campaign using the Gul Bakes blue brand system.'],
['Marketing funnel & campaign plan','Quratulain Shakeel',5,9,'To do','Medium',4000,0,['gb-t17','gb-t21'],'Document awareness, consideration, conversion and retention touchpoints across social, store and email.'],
['Analytics & measurement plan','Quratulain Shakeel',7,11,'To do','Medium',3500,0,['gb-t22'],'Define practical KPIs for traffic, product discovery, conversion, email and campaign learning.'],
['Final launch QA & link validation','Quratulain Shakeel',10,13,'To do','High',4500,0,['gb-t12','gb-t14','gb-t16','gb-t18','gb-t21'],'Run final checks across links, menus, checkout path, mobile layouts, content and key store actions.'],
['Portfolio documentation & evidence','Quratulain Shakeel',11,15,'To do','High',5000,0,['gb-t23','gb-t24'],'Capture the project story, roles, screenshots, decisions, deliverables and links for the portfolio.'],
['Presentation / handoff pack','Gulnaz Akhtar',14,17,'To do','Medium',4000,0,['gb-t25'],'Prepare a concise project handoff and presentation showing the work from setup to marketing.'],
['Post-launch improvement backlog','Quratulain Shakeel',16,20,'To do','Low',2500,0,['gb-t24'],'Collect non-critical improvements for later prioritization instead of expanding launch scope.']
];
const tasks=rows.map((r,i)=>({id:'gb-t'+i,title:r[0],owner:r[1],start:offsetDate(r[2]),due:offsetDate(r[3]),status:r[4],priority:r[5],estimate:r[6],actual:r[7],deps:r[8],notes:r[9]}));
return {
id:uid(),
name:'Gul Bakes · Ecommerce launch & growth',
description:'Portfolio workspace for the Gul Bakes Shopify project: plan, build, market, test and document the complete ecommerce experience created by teammates Quratulain Shakeel and Gulnaz Akhtar.',
budget:135000,
currency:'PKR',
demo:true,
tasks,
risks:[
{id:uid(),title:'Incorrect collection or menu links create dead-end customer journeys',owner:'Quratulain Shakeel',probability:4,impact:4,response:'Maintain a launch checklist and test every header, footer, collection and CTA link on desktop and mobile.',status:'Open'},
{id:uid(),title:'Product information becomes inconsistent across Shopify and social/catalog channels',owner:'Gulnaz Akhtar',probability:3,impact:4,response:'Use one product-data source and verify titles, prices, images and availability before each sync.',status:'Open'},
{id:uid(),title:'Mobile sections become crowded or break the premium visual system',owner:'Quratulain Shakeel',probability:4,impact:3,response:'Test key breakpoints after every custom section and keep critical content visible without horizontal breakage.',status:'Open'},
{id:uid(),title:'Scope grows through repeated design changes close to launch',owner:'Quratulain Shakeel',probability:3,impact:4,response:'Route new requests through the change log and move non-critical ideas to the post-launch backlog.',status:'Open'},
{id:uid(),title:'Email sender or catalog configuration delays marketing activation',owner:'Gulnaz Akhtar',probability:2,impact:3,response:'Complete account setup early and test sender/catalog approval before the campaign launch date.',status:'Open'}
],
changes:[
{id:uid(),title:'Add premium video section to the homepage',reason:'A short branded cake-design video can strengthen the premium storytelling while matching the navy visual system.',amount:6500,days:2,status:'Pending',decision:''},
{id:uid(),title:'Expand homepage with Signature Details and Gift Edit sections',reason:'Adds richer craftsmanship and gifting storytelling to the storefront.',amount:4500,days:1,status:'Approved',decision:'Approved because the sections reinforce the brand story and can be implemented without changing checkout scope.'}
],
activity:[{at:new Date().toISOString(),text:'Gul Bakes portfolio demo loaded with an end-to-end ecommerce project plan. Replace illustrative dates/costs with measured records if using this as formal reporting.'}]
};}
